---
services:
  livefy-postgres:
    image: postgres:14.2
    container_name: livefy-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - livefy-postgres-data:/var/lib/postgresql/data
  livefy-keycloak:
    image: jboss/keycloak:14.0.0
    container_name: livefy-keycloak
    restart: always
    ports:
      - 8180:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=pass
      - DB_VENDOR=postgres
      - DB_ADDR=livefy-postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - KEYCLOAK_FRONTEND_URL=http://localhost:8180/auth/
    depends_on:
      - livefy-postgres
  livefy-consul:
    image: consul:1.11.4
    container_name: livefy-consul
    restart: always
    ports:
      - 8500:8500
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - livefy-consul-data:/consul/data
  livefy-redis:
    image: redis:6.2.6
    container_name: livefy-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - livefy-redis-data:/data
  livefy-zookeeper:
    image: bitnami/zookeeper:3.8.0
    container_name: livefy-zookeeper
    ports:
      - 2181:2181
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - livefy-zookeeper-data:/bitnami/zookeeper
  livefy-kafka1:
    image: bitnami/kafka:3.1.0
    container_name: livefy-kafka1
    ports:
      - 9093:8092
    restart: always
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: livefy-zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:8092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://livefy-kafka1:9092,EXTERNAL://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - livefy-zookeeper
    volumes:
      - livefy-kafka1-data:/bitnami/kafka
  livefy-kafka2:
    image: bitnami/kafka:3.1.0
    container_name: livefy-kafka2
    ports:
      - 9094:8092
    restart: always
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: livefy-zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:8092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://livefy-kafka2:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - livefy-zookeeper
    volumes:
      - livefy-kafka2-data:/bitnami/kafka
  livefy-kafka3:
    image: bitnami/kafka:3.1.0
    container_name: livefy-kafka3
    ports:
      - 9095:8092
    restart: always
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: livefy-zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:8092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://livefy-kafka3:9092,EXTERNAL://localhost:9095
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - livefy-zookeeper
    volumes:
      - livefy-kafka3-data:/bitnami/kafka
  livefy-kafdrop:
    image: obsidiandynamics/kafdrop:3.29.0
    container_name: livefy-kafdrop
    restart: always
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: livefy-kafka1:9092,livefy-kafka2:9092,livefy-kafka3:9092
      JVM_OPTS: -Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation
        -XX:+UseStringDeduplication -noverify
    depends_on:
      - livefy-kafka1
      - livefy-kafka2
      - livefy-kafka3
  livefy-zipkin:
    image: openzipkin/zipkin:2.23.16
    container_name: livefy-zipkin
    restart: always
    ports:
      - 9411:9411
    environment:
      - STORAGE_TYPE=mem
volumes:
  livefy-postgres-data:
    name: livefy-postgres-data
  livefy-consul-data:
    name: livefy-consul-data
  livefy-redis-data:
    name: livefy-redis-data
  livefy-zookeeper-data:
    name: livefy-zookeeper-data
  livefy-kafka1-data:
    name: livefy-kafka1-data
  livefy-kafka2-data:
    name: livefy-kafka2-data
  livefy-kafka3-data:
    name: livefy-kafka3-data
networks:
  default:
    name: livefy-messaging
