apiVersion: v1
kind: Service
metadata:
  name: livefy-users-services
  labels:
    app: livefy-users-services
    group: livefy.app
spec:
  ports:
    - name: http
      port: &target 8080
      protocol: TCP
      targetPort: *target
  selector:
    app: livefy-users-services
    group: livefy.app
  type: NodePort