apiVersion: apps/v1
kind: Deployment
metadata:
  name: livefy-users-services
  labels:
    app: livefy-users-services
    version: 0.0.1-SNAPSHOT
    group: livefy.app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livefy-users-services
      group: livefy.app
  template:
    metadata:
      labels:
        app: livefy-users-services
        version: 0.0.1-SNAPSHOT
        group: livefy.app
    spec:
      containers:
        - name: livefy-users-services
          image: livefy/livefy-messaging/livefy-users-services:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: http`
              containerPort: 8080