apiVersion: v1
kind: Service
metadata:
  labels:
    app: livefy-api-gateway
    group: livefy.app
  name: livefy-api-gateway
spec:
  ports:
    - name: http
      port: &target 8080
      protocol: TCP
      targetPort: *target
  selector:
    app: livefy-api-gateway
    group: livefy.app
  type: LoadBalancer